// <auto-generated />
using System;
using Deskbuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deskbuddy.Migrations
{
    [DbContext(typeof(DeskbuddyContext))]
    [Migration("20240715005748_seedingRoom")]
    partial class seedingRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0d8d0d49-b52e-4158-b4fd-1b282046c0b7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdf6ce9d-0b46-4f1f-bece-628ec7bf825f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH4e7Ee/LBtSIKS9T3sz2uiKBOdZF5xWmGaLNXusNdfnQ1K+LEHuYm8ZfFUUYR8FNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8bbfeedf-da6b-42c4-8329-4c5b7f569feb",
                            TwoFactorEnabled = false,
                            UserName = "admin@abc.com"
                        },
                        new
                        {
                            Id = "2ed38f27-8671-4f8c-bdcc-5d95235d90f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca7f1f5e-a6d8-4188-962d-0e5e364be0f6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SEKRETARIAT@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFf/aINQwfWZut3BQefH8F46QMs7cMcUCuhgJyunjaBvGWYxQUb5TldEqGm5nN2QQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35a05ee6-93c9-446b-ba79-aeb475df2dee",
                            TwoFactorEnabled = false,
                            UserName = "sekretariat@abc.com"
                        },
                        new
                        {
                            Id = "3bf84860-8b94-4349-8b09-ccc4966bdf6a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8152840d-fe90-4d71-901b-e44717d009c6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MITARBEITER@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBHYTsNSKog/X0FTCT0Fr9rMxER9nyezNVnpd/ZE+aQBN09UOaQ4ulYp/4UmSdgPDw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52575cf6-b800-4268-864c-0b2f3d2b58cc",
                            TwoFactorEnabled = false,
                            UserName = "mitarbeiter@abc.com"
                        },
                        new
                        {
                            Id = "d88180fc-cd80-4087-a1f9-e1f8b5bded06",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be307c9a-4afc-4081-afeb-df218e9475db",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ABTEILUNGSLEITER@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB5asrkZOr55ylQ9Vwmab/bxta7vS5NAbOMZbeTON8AKIpdtGHhfiu3irDQj4hzknA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "29cd5c2a-132e-40bf-b158-8017f917bced",
                            TwoFactorEnabled = false,
                            UserName = "abteilungsleiter@abc.com"
                        });
                });

            modelBuilder.Entity("Deskbuddy.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chief = "Anton Meier",
                            Name = "Finanzen"
                        },
                        new
                        {
                            Id = 2,
                            Chief = "Bernd Schmidt",
                            Name = "Einkauf"
                        },
                        new
                        {
                            Id = 3,
                            Chief = "Clara Fischer",
                            Name = "Verkauf"
                        },
                        new
                        {
                            Id = 4,
                            Chief = "Dieter Weber",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Chief = "Eva Müller",
                            Name = "KundenSupport"
                        });
                });

            modelBuilder.Entity("Deskbuddy.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            Name = "Greta Bauer"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 4,
                            Name = "Bernd Weber"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 4,
                            Name = "Anton Schmidt"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Name = "Johann Becker"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            Name = "Heinz Becker"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 5,
                            Name = "Johann Wagner"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 5,
                            Name = "Bernd Fischer"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Name = "Greta Schmidt"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            Name = "Eva Schmidt"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            Name = "Anton Bauer"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 2,
                            Name = "Heinz Koch"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Name = "Anton Weber"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Name = "Heinz Müller"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 4,
                            Name = "Greta Richter"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 1,
                            Name = "Ingrid Meier"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 4,
                            Name = "Friedrich Becker"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 1,
                            Name = "Eva Meier"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 1,
                            Name = "Heinz Koch"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 2,
                            Name = "Greta Schmidt"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 3,
                            Name = "Heinz Bauer"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 5,
                            Name = "Friedrich Richter"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 3,
                            Name = "Anton Wagner"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 3,
                            Name = "Bernd Weber"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 4,
                            Name = "Friedrich Koch"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 2,
                            Name = "Johann Weber"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 4,
                            Name = "Friedrich Meier"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 3,
                            Name = "Bernd Weber"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 2,
                            Name = "Clara Weber"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 1,
                            Name = "Dieter Müller"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            Name = "Friedrich Wagner"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 5,
                            Name = "Heinz Richter"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 2,
                            Name = "Heinz Fischer"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 3,
                            Name = "Dieter Meier"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 3,
                            Name = "Heinz Fischer"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 5,
                            Name = "Eva Müller"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 5,
                            Name = "Bernd Bauer"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 4,
                            Name = "Friedrich Richter"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 3,
                            Name = "Anton Weber"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 5,
                            Name = "Johann Bauer"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 5,
                            Name = "Anton Becker"
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 4,
                            Name = "Dieter Müller"
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 4,
                            Name = "Johann Bauer"
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 5,
                            Name = "Bernd Wagner"
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 4,
                            Name = "Clara Weber"
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 3,
                            Name = "Friedrich Koch"
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 4,
                            Name = "Friedrich Fischer"
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 4,
                            Name = "Eva Schmidt"
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 2,
                            Name = "Ingrid Richter"
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 3,
                            Name = "Eva Schmidt"
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 2,
                            Name = "Johann Meier"
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 1,
                            Name = "Heinz Fischer"
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 1,
                            Name = "Friedrich Koch"
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 1,
                            Name = "Clara Becker"
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 3,
                            Name = "Dieter Becker"
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 2,
                            Name = "Eva Wagner"
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 5,
                            Name = "Dieter Richter"
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 2,
                            Name = "Greta Bauer"
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 2,
                            Name = "Greta Weber"
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 5,
                            Name = "Bernd Bauer"
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 5,
                            Name = "Clara Wagner"
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 3,
                            Name = "Clara Schmidt"
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 2,
                            Name = "Johann Wagner"
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 2,
                            Name = "Anton Schmidt"
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 4,
                            Name = "Eva Becker"
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 3,
                            Name = "Dieter Richter"
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 3,
                            Name = "Heinz Becker"
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 2,
                            Name = "Anton Koch"
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 2,
                            Name = "Dieter Richter"
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 5,
                            Name = "Heinz Weber"
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 4,
                            Name = "Ingrid Weber"
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 4,
                            Name = "Johann Meier"
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 5,
                            Name = "Eva Weber"
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 3,
                            Name = "Friedrich Koch"
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 3,
                            Name = "Friedrich Koch"
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 2,
                            Name = "Anton Fischer"
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 1,
                            Name = "Heinz Meier"
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 5,
                            Name = "Eva Müller"
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 1,
                            Name = "Ingrid Weber"
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 3,
                            Name = "Greta Becker"
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 5,
                            Name = "Eva Wagner"
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 3,
                            Name = "Ingrid Schmidt"
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 5,
                            Name = "Eva Becker"
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 4,
                            Name = "Heinz Müller"
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 3,
                            Name = "Eva Wagner"
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 2,
                            Name = "Eva Schmidt"
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 5,
                            Name = "Heinz Bauer"
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 4,
                            Name = "Friedrich Weber"
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 5,
                            Name = "Dieter Meier"
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 5,
                            Name = "Dieter Wagner"
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 5,
                            Name = "Bernd Bauer"
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 5,
                            Name = "Anton Weber"
                        },
                        new
                        {
                            Id = 92,
                            DepartmentId = 2,
                            Name = "Dieter Weber"
                        },
                        new
                        {
                            Id = 93,
                            DepartmentId = 3,
                            Name = "Eva Becker"
                        },
                        new
                        {
                            Id = 94,
                            DepartmentId = 2,
                            Name = "Greta Richter"
                        },
                        new
                        {
                            Id = 95,
                            DepartmentId = 4,
                            Name = "Friedrich Müller"
                        },
                        new
                        {
                            Id = 96,
                            DepartmentId = 3,
                            Name = "Eva Richter"
                        },
                        new
                        {
                            Id = 97,
                            DepartmentId = 2,
                            Name = "Eva Wagner"
                        },
                        new
                        {
                            Id = 98,
                            DepartmentId = 2,
                            Name = "Friedrich Bauer"
                        },
                        new
                        {
                            Id = 99,
                            DepartmentId = 4,
                            Name = "Heinz Weber"
                        },
                        new
                        {
                            Id = 100,
                            DepartmentId = 2,
                            Name = "Ingrid Becker"
                        },
                        new
                        {
                            Id = 101,
                            DepartmentId = 3,
                            Name = "Heinz Müller"
                        },
                        new
                        {
                            Id = 102,
                            DepartmentId = 1,
                            Name = "Ingrid Schmidt"
                        },
                        new
                        {
                            Id = 103,
                            DepartmentId = 5,
                            Name = "Heinz Meier"
                        },
                        new
                        {
                            Id = 104,
                            DepartmentId = 4,
                            Name = "Anton Meier"
                        },
                        new
                        {
                            Id = 105,
                            DepartmentId = 2,
                            Name = "Clara Koch"
                        },
                        new
                        {
                            Id = 106,
                            DepartmentId = 1,
                            Name = "Bernd Richter"
                        },
                        new
                        {
                            Id = 107,
                            DepartmentId = 5,
                            Name = "Eva Bauer"
                        },
                        new
                        {
                            Id = 108,
                            DepartmentId = 4,
                            Name = "Greta Weber"
                        },
                        new
                        {
                            Id = 109,
                            DepartmentId = 3,
                            Name = "Ingrid Fischer"
                        },
                        new
                        {
                            Id = 110,
                            DepartmentId = 4,
                            Name = "Heinz Fischer"
                        },
                        new
                        {
                            Id = 111,
                            DepartmentId = 4,
                            Name = "Johann Becker"
                        },
                        new
                        {
                            Id = 112,
                            DepartmentId = 2,
                            Name = "Ingrid Müller"
                        },
                        new
                        {
                            Id = 113,
                            DepartmentId = 3,
                            Name = "Eva Becker"
                        },
                        new
                        {
                            Id = 114,
                            DepartmentId = 4,
                            Name = "Ingrid Weber"
                        },
                        new
                        {
                            Id = 115,
                            DepartmentId = 4,
                            Name = "Heinz Meier"
                        },
                        new
                        {
                            Id = 116,
                            DepartmentId = 4,
                            Name = "Anton Richter"
                        },
                        new
                        {
                            Id = 117,
                            DepartmentId = 2,
                            Name = "Dieter Müller"
                        },
                        new
                        {
                            Id = 118,
                            DepartmentId = 2,
                            Name = "Clara Müller"
                        },
                        new
                        {
                            Id = 119,
                            DepartmentId = 2,
                            Name = "Johann Müller"
                        },
                        new
                        {
                            Id = 120,
                            DepartmentId = 1,
                            Name = "Heinz Müller"
                        },
                        new
                        {
                            Id = 121,
                            DepartmentId = 2,
                            Name = "Greta Meier"
                        },
                        new
                        {
                            Id = 122,
                            DepartmentId = 3,
                            Name = "Eva Richter"
                        },
                        new
                        {
                            Id = 123,
                            DepartmentId = 1,
                            Name = "Eva Schmidt"
                        });
                });

            modelBuilder.Entity("Deskbuddy.Models.Occupancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Occupancies", (string)null);
                });

            modelBuilder.Entity("Deskbuddy.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "R0001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "R0011"
                        },
                        new
                        {
                            Id = 3,
                            Name = "R0021"
                        },
                        new
                        {
                            Id = 4,
                            Name = "R0031"
                        },
                        new
                        {
                            Id = 5,
                            Name = "R0041"
                        },
                        new
                        {
                            Id = 6,
                            Name = "R0051"
                        },
                        new
                        {
                            Id = 7,
                            Name = "R0061"
                        },
                        new
                        {
                            Id = 8,
                            Name = "R0071"
                        },
                        new
                        {
                            Id = 9,
                            Name = "R0081"
                        },
                        new
                        {
                            Id = 10,
                            Name = "R0091"
                        },
                        new
                        {
                            Id = 11,
                            Name = "R00101"
                        },
                        new
                        {
                            Id = 12,
                            Name = "R00111"
                        },
                        new
                        {
                            Id = 13,
                            Name = "R00121"
                        },
                        new
                        {
                            Id = 14,
                            Name = "R00131"
                        },
                        new
                        {
                            Id = 15,
                            Name = "R00141"
                        },
                        new
                        {
                            Id = 16,
                            Name = "R00151"
                        },
                        new
                        {
                            Id = 17,
                            Name = "R00161"
                        },
                        new
                        {
                            Id = 18,
                            Name = "R00171"
                        },
                        new
                        {
                            Id = 19,
                            Name = "R00181"
                        },
                        new
                        {
                            Id = 20,
                            Name = "R00191"
                        },
                        new
                        {
                            Id = 21,
                            Name = "R00201"
                        },
                        new
                        {
                            Id = 22,
                            Name = "R00211"
                        },
                        new
                        {
                            Id = 23,
                            Name = "R00221"
                        },
                        new
                        {
                            Id = 24,
                            Name = "R00231"
                        },
                        new
                        {
                            Id = 25,
                            Name = "R00241"
                        },
                        new
                        {
                            Id = 26,
                            Name = "R00251"
                        },
                        new
                        {
                            Id = 27,
                            Name = "R00261"
                        },
                        new
                        {
                            Id = 28,
                            Name = "R00271"
                        },
                        new
                        {
                            Id = 29,
                            Name = "R00281"
                        },
                        new
                        {
                            Id = 30,
                            Name = "R00291"
                        },
                        new
                        {
                            Id = 31,
                            Name = "R00301"
                        },
                        new
                        {
                            Id = 32,
                            Name = "R00311"
                        },
                        new
                        {
                            Id = 33,
                            Name = "R00321"
                        },
                        new
                        {
                            Id = 34,
                            Name = "R00331"
                        },
                        new
                        {
                            Id = 35,
                            Name = "R00341"
                        },
                        new
                        {
                            Id = 36,
                            Name = "R00351"
                        },
                        new
                        {
                            Id = 37,
                            Name = "R00361"
                        },
                        new
                        {
                            Id = 38,
                            Name = "R00371"
                        },
                        new
                        {
                            Id = 39,
                            Name = "R00381"
                        },
                        new
                        {
                            Id = 40,
                            Name = "R00391"
                        },
                        new
                        {
                            Id = 41,
                            Name = "R00401"
                        },
                        new
                        {
                            Id = 42,
                            Name = "R00411"
                        },
                        new
                        {
                            Id = 43,
                            Name = "R00421"
                        },
                        new
                        {
                            Id = 44,
                            Name = "R00431"
                        },
                        new
                        {
                            Id = 45,
                            Name = "R00441"
                        },
                        new
                        {
                            Id = 46,
                            Name = "R00451"
                        },
                        new
                        {
                            Id = 47,
                            Name = "R00461"
                        },
                        new
                        {
                            Id = 48,
                            Name = "R00471"
                        },
                        new
                        {
                            Id = 49,
                            Name = "R00481"
                        },
                        new
                        {
                            Id = 50,
                            Name = "R00491"
                        },
                        new
                        {
                            Id = 51,
                            Name = "R00501"
                        },
                        new
                        {
                            Id = 52,
                            Name = "R00511"
                        },
                        new
                        {
                            Id = 53,
                            Name = "R00521"
                        },
                        new
                        {
                            Id = 54,
                            Name = "R00531"
                        },
                        new
                        {
                            Id = 55,
                            Name = "R00541"
                        },
                        new
                        {
                            Id = 56,
                            Name = "R00551"
                        },
                        new
                        {
                            Id = 57,
                            Name = "R00561"
                        },
                        new
                        {
                            Id = 58,
                            Name = "R00571"
                        },
                        new
                        {
                            Id = 59,
                            Name = "R00581"
                        },
                        new
                        {
                            Id = 60,
                            Name = "R00591"
                        },
                        new
                        {
                            Id = 61,
                            Name = "R00601"
                        },
                        new
                        {
                            Id = 62,
                            Name = "R00611"
                        },
                        new
                        {
                            Id = 63,
                            Name = "R00621"
                        },
                        new
                        {
                            Id = 64,
                            Name = "R00631"
                        },
                        new
                        {
                            Id = 65,
                            Name = "R00641"
                        },
                        new
                        {
                            Id = 66,
                            Name = "R00651"
                        },
                        new
                        {
                            Id = 67,
                            Name = "R00661"
                        },
                        new
                        {
                            Id = 68,
                            Name = "R00671"
                        },
                        new
                        {
                            Id = 69,
                            Name = "R00681"
                        },
                        new
                        {
                            Id = 70,
                            Name = "R00691"
                        },
                        new
                        {
                            Id = 71,
                            Name = "R00701"
                        },
                        new
                        {
                            Id = 72,
                            Name = "R00711"
                        },
                        new
                        {
                            Id = 73,
                            Name = "R00721"
                        },
                        new
                        {
                            Id = 74,
                            Name = "R00731"
                        },
                        new
                        {
                            Id = 75,
                            Name = "R00741"
                        },
                        new
                        {
                            Id = 76,
                            Name = "R00751"
                        },
                        new
                        {
                            Id = 77,
                            Name = "R00761"
                        },
                        new
                        {
                            Id = 78,
                            Name = "R00771"
                        },
                        new
                        {
                            Id = 79,
                            Name = "R00781"
                        },
                        new
                        {
                            Id = 80,
                            Name = "R00791"
                        },
                        new
                        {
                            Id = 81,
                            Name = "R00801"
                        },
                        new
                        {
                            Id = 82,
                            Name = "R00811"
                        },
                        new
                        {
                            Id = 83,
                            Name = "R00821"
                        },
                        new
                        {
                            Id = 84,
                            Name = "R00831"
                        },
                        new
                        {
                            Id = 85,
                            Name = "R00841"
                        },
                        new
                        {
                            Id = 86,
                            Name = "R00851"
                        },
                        new
                        {
                            Id = 87,
                            Name = "R00861"
                        },
                        new
                        {
                            Id = 88,
                            Name = "R00871"
                        },
                        new
                        {
                            Id = 89,
                            Name = "R00881"
                        },
                        new
                        {
                            Id = 90,
                            Name = "R00891"
                        },
                        new
                        {
                            Id = 91,
                            Name = "R00901"
                        },
                        new
                        {
                            Id = 92,
                            Name = "R00911"
                        },
                        new
                        {
                            Id = 93,
                            Name = "R00921"
                        },
                        new
                        {
                            Id = 94,
                            Name = "R00931"
                        },
                        new
                        {
                            Id = 95,
                            Name = "R00941"
                        },
                        new
                        {
                            Id = 96,
                            Name = "R00951"
                        },
                        new
                        {
                            Id = 97,
                            Name = "R00961"
                        },
                        new
                        {
                            Id = 98,
                            Name = "R00971"
                        },
                        new
                        {
                            Id = 99,
                            Name = "R00981"
                        },
                        new
                        {
                            Id = 100,
                            Name = "R00991"
                        },
                        new
                        {
                            Id = 101,
                            Name = "R001001"
                        },
                        new
                        {
                            Id = 102,
                            Name = "R001011"
                        },
                        new
                        {
                            Id = 103,
                            Name = "R001021"
                        },
                        new
                        {
                            Id = 104,
                            Name = "R001031"
                        },
                        new
                        {
                            Id = 105,
                            Name = "R001041"
                        },
                        new
                        {
                            Id = 106,
                            Name = "R001051"
                        },
                        new
                        {
                            Id = 107,
                            Name = "R001061"
                        },
                        new
                        {
                            Id = 108,
                            Name = "R001071"
                        },
                        new
                        {
                            Id = 109,
                            Name = "R001081"
                        },
                        new
                        {
                            Id = 110,
                            Name = "R001091"
                        },
                        new
                        {
                            Id = 111,
                            Name = "R001101"
                        },
                        new
                        {
                            Id = 112,
                            Name = "R001111"
                        },
                        new
                        {
                            Id = 113,
                            Name = "R001121"
                        },
                        new
                        {
                            Id = 114,
                            Name = "R001131"
                        },
                        new
                        {
                            Id = 115,
                            Name = "R001141"
                        },
                        new
                        {
                            Id = 116,
                            Name = "R001151"
                        },
                        new
                        {
                            Id = 117,
                            Name = "R001161"
                        },
                        new
                        {
                            Id = 118,
                            Name = "R001171"
                        },
                        new
                        {
                            Id = 119,
                            Name = "R001181"
                        },
                        new
                        {
                            Id = 120,
                            Name = "R001191"
                        },
                        new
                        {
                            Id = 121,
                            Name = "R001201"
                        },
                        new
                        {
                            Id = 122,
                            Name = "R001211"
                        },
                        new
                        {
                            Id = 123,
                            Name = "R001221"
                        },
                        new
                        {
                            Id = 124,
                            Name = "R001231"
                        },
                        new
                        {
                            Id = 125,
                            Name = "R001241"
                        },
                        new
                        {
                            Id = 126,
                            Name = "R001251"
                        },
                        new
                        {
                            Id = 127,
                            Name = "R001261"
                        },
                        new
                        {
                            Id = 128,
                            Name = "R001271"
                        },
                        new
                        {
                            Id = 129,
                            Name = "R001281"
                        },
                        new
                        {
                            Id = 130,
                            Name = "R001291"
                        },
                        new
                        {
                            Id = 131,
                            Name = "R001301"
                        },
                        new
                        {
                            Id = 132,
                            Name = "R001311"
                        },
                        new
                        {
                            Id = 133,
                            Name = "R001321"
                        },
                        new
                        {
                            Id = 134,
                            Name = "R001331"
                        },
                        new
                        {
                            Id = 135,
                            Name = "R001341"
                        },
                        new
                        {
                            Id = 136,
                            Name = "R001351"
                        },
                        new
                        {
                            Id = 137,
                            Name = "R001361"
                        },
                        new
                        {
                            Id = 138,
                            Name = "R001371"
                        },
                        new
                        {
                            Id = 139,
                            Name = "R001381"
                        },
                        new
                        {
                            Id = 140,
                            Name = "R001391"
                        },
                        new
                        {
                            Id = 141,
                            Name = "R001401"
                        },
                        new
                        {
                            Id = 142,
                            Name = "R001411"
                        },
                        new
                        {
                            Id = 143,
                            Name = "R001421"
                        },
                        new
                        {
                            Id = 144,
                            Name = "R001431"
                        },
                        new
                        {
                            Id = 145,
                            Name = "R001441"
                        },
                        new
                        {
                            Id = 146,
                            Name = "R001451"
                        },
                        new
                        {
                            Id = 147,
                            Name = "R001461"
                        },
                        new
                        {
                            Id = 148,
                            Name = "R001471"
                        },
                        new
                        {
                            Id = 149,
                            Name = "R001481"
                        },
                        new
                        {
                            Id = 150,
                            Name = "R001491"
                        },
                        new
                        {
                            Id = 151,
                            Name = "R001501"
                        },
                        new
                        {
                            Id = 152,
                            Name = "R001511"
                        },
                        new
                        {
                            Id = 153,
                            Name = "R001521"
                        },
                        new
                        {
                            Id = 154,
                            Name = "R001531"
                        },
                        new
                        {
                            Id = 155,
                            Name = "R001541"
                        },
                        new
                        {
                            Id = 156,
                            Name = "R001551"
                        },
                        new
                        {
                            Id = 157,
                            Name = "R001561"
                        },
                        new
                        {
                            Id = 158,
                            Name = "R001571"
                        },
                        new
                        {
                            Id = 159,
                            Name = "R001581"
                        },
                        new
                        {
                            Id = 160,
                            Name = "R001591"
                        },
                        new
                        {
                            Id = 161,
                            Name = "R001601"
                        },
                        new
                        {
                            Id = 162,
                            Name = "R001611"
                        },
                        new
                        {
                            Id = 163,
                            Name = "R001621"
                        },
                        new
                        {
                            Id = 164,
                            Name = "R001631"
                        },
                        new
                        {
                            Id = 165,
                            Name = "R001641"
                        },
                        new
                        {
                            Id = 166,
                            Name = "R001651"
                        },
                        new
                        {
                            Id = 167,
                            Name = "R001661"
                        },
                        new
                        {
                            Id = 168,
                            Name = "R001671"
                        },
                        new
                        {
                            Id = 169,
                            Name = "R001681"
                        },
                        new
                        {
                            Id = 170,
                            Name = "R001691"
                        },
                        new
                        {
                            Id = 171,
                            Name = "R001701"
                        },
                        new
                        {
                            Id = 172,
                            Name = "R001711"
                        },
                        new
                        {
                            Id = 173,
                            Name = "R001721"
                        },
                        new
                        {
                            Id = 174,
                            Name = "R001731"
                        },
                        new
                        {
                            Id = 175,
                            Name = "R001741"
                        },
                        new
                        {
                            Id = 176,
                            Name = "R001751"
                        },
                        new
                        {
                            Id = 177,
                            Name = "R001761"
                        },
                        new
                        {
                            Id = 178,
                            Name = "R001771"
                        },
                        new
                        {
                            Id = 179,
                            Name = "R001781"
                        },
                        new
                        {
                            Id = 180,
                            Name = "R001791"
                        },
                        new
                        {
                            Id = 181,
                            Name = "R001801"
                        },
                        new
                        {
                            Id = 182,
                            Name = "R001811"
                        },
                        new
                        {
                            Id = 183,
                            Name = "R001821"
                        },
                        new
                        {
                            Id = 184,
                            Name = "R001831"
                        },
                        new
                        {
                            Id = 185,
                            Name = "R001841"
                        },
                        new
                        {
                            Id = 186,
                            Name = "R001851"
                        },
                        new
                        {
                            Id = 187,
                            Name = "R001861"
                        },
                        new
                        {
                            Id = 188,
                            Name = "R001871"
                        },
                        new
                        {
                            Id = 189,
                            Name = "R001881"
                        },
                        new
                        {
                            Id = 190,
                            Name = "R001891"
                        },
                        new
                        {
                            Id = 191,
                            Name = "R001901"
                        },
                        new
                        {
                            Id = 192,
                            Name = "R001911"
                        },
                        new
                        {
                            Id = 193,
                            Name = "R001921"
                        },
                        new
                        {
                            Id = 194,
                            Name = "R001931"
                        },
                        new
                        {
                            Id = 195,
                            Name = "R001941"
                        },
                        new
                        {
                            Id = 196,
                            Name = "R001951"
                        },
                        new
                        {
                            Id = 197,
                            Name = "R001961"
                        },
                        new
                        {
                            Id = 198,
                            Name = "R001971"
                        },
                        new
                        {
                            Id = 199,
                            Name = "R001981"
                        },
                        new
                        {
                            Id = 200,
                            Name = "R001991"
                        });
                });

            modelBuilder.Entity("Deskbuddy.Models.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Workplaces", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7ac76fc0-c50d-4f77-8d96-df8da588d757",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "dd515b4d-ff02-43a4-8be8-52007bd85446",
                            Name = "Sekretariat",
                            NormalizedName = "SEKRETARIAT"
                        },
                        new
                        {
                            Id = "ca57bdb0-b7ca-4f88-a3b2-9a3c0a08d5d8",
                            Name = "Mitarbeiter",
                            NormalizedName = "MITARBEITER"
                        },
                        new
                        {
                            Id = "87cdce2b-dd19-4830-83e0-ac26a0997d03",
                            Name = "Abteilungsleiter",
                            NormalizedName = "ABTEILUNGSLEITER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0d8d0d49-b52e-4158-b4fd-1b282046c0b7",
                            RoleId = "7ac76fc0-c50d-4f77-8d96-df8da588d757"
                        },
                        new
                        {
                            UserId = "2ed38f27-8671-4f8c-bdcc-5d95235d90f3",
                            RoleId = "dd515b4d-ff02-43a4-8be8-52007bd85446"
                        },
                        new
                        {
                            UserId = "3bf84860-8b94-4349-8b09-ccc4966bdf6a",
                            RoleId = "ca57bdb0-b7ca-4f88-a3b2-9a3c0a08d5d8"
                        },
                        new
                        {
                            UserId = "d88180fc-cd80-4087-a1f9-e1f8b5bded06",
                            RoleId = "87cdce2b-dd19-4830-83e0-ac26a0997d03"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Deskbuddy.Models.Employee", b =>
                {
                    b.HasOne("Deskbuddy.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Deskbuddy.Models.Occupancy", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deskbuddy.Models.Workplace", "Workplace")
                        .WithMany("Occupancies")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Deskbuddy.Models.Workplace", b =>
                {
                    b.HasOne("Deskbuddy.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deskbuddy.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Deskbuddy.Models.Workplace", b =>
                {
                    b.Navigation("Occupancies");
                });
#pragma warning restore 612, 618
        }
    }
}
