// <auto-generated />
using System;
using Deskbuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deskbuddy.Migrations
{
    [DbContext(typeof(DeskbuddyContext))]
    [Migration("20240714224735_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aa167027-4226-4341-bc45-fd9a0748f70a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6f82f3d-5b20-4664-bc68-2355d58dc05e",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEItOGYKl7XBRqKaRiqSd53YACHq1XUFvLLUoIdN6gcUbve2bTdczniSXV2m+Luyo2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c737b869-03b4-4176-9f36-8d1534e9b2ce",
                            TwoFactorEnabled = false,
                            UserName = "admin@abc.com"
                        },
                        new
                        {
                            Id = "75b19fb1-7184-4a1e-bfaf-39d157353db2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d68a6a89-af57-49bc-be1f-3ece7ff223f1",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SEKRETARIAT@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMyzqjs9+Vj20i8Qzd2DPYPRqM8pMx9wiLBlMoCeoxyap05aWIVGuvL6P6/1OBjNhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5d7cb70c-a3ca-4220-8b4f-2eeee01fa800",
                            TwoFactorEnabled = false,
                            UserName = "sekretariat@abc.com"
                        },
                        new
                        {
                            Id = "1f6695ef-d669-48b4-b194-bd92d17057e0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0853fd04-b0f2-4a8a-8a90-21a745e12b95",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MITARBEITER@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPN9OyopAGVGoGkzLWoPnJox64SQOGKR6CYay5coOMHubaZ6UQHGNk+W5iiKST/Q7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6773ea53-c040-4331-ac23-b31f4e058c4a",
                            TwoFactorEnabled = false,
                            UserName = "mitarbeiter@abc.com"
                        },
                        new
                        {
                            Id = "902f1326-2d22-411a-8c06-6732ad46aff4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca435d41-d414-483a-8d14-c86da4f1f33f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ABTEILUNGSLEITER@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN+EQMNwe/ghlOYVeZmNExS76hl1nJ6N7JcEINrafz4cDURFvS+dy84CHqkQ/XUhXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e4fb2e88-b5fa-49eb-ab54-a880323d7ab4",
                            TwoFactorEnabled = false,
                            UserName = "abteilungsleiter@abc.com"
                        });
                });

            modelBuilder.Entity("Deskbuddy.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chief = "Anton Meier",
                            Name = "Finanzen"
                        },
                        new
                        {
                            Id = 2,
                            Chief = "Bernd Schmidt",
                            Name = "Einkauf"
                        },
                        new
                        {
                            Id = 3,
                            Chief = "Clara Fischer",
                            Name = "Verkauf"
                        },
                        new
                        {
                            Id = 4,
                            Chief = "Dieter Weber",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Chief = "Eva Müller",
                            Name = "KundenSupport"
                        });
                });

            modelBuilder.Entity("Deskbuddy.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 4,
                            Name = "Heinz Schmidt"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Eva Fischer"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 5,
                            Name = "Greta Wagner"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Dieter Weber"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Ingrid Meier"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 5,
                            Name = "Bernd Meier"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            Name = "Johann Becker"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Name = "Eva Müller"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            Name = "Clara Weber"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 4,
                            Name = "Heinz Koch"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Name = "Friedrich Weber"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 3,
                            Name = "Greta Richter"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Name = "Anton Richter"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 2,
                            Name = "Greta Meier"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 5,
                            Name = "Heinz Schmidt"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 4,
                            Name = "Dieter Müller"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 1,
                            Name = "Eva Bauer"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 2,
                            Name = "Dieter Weber"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 3,
                            Name = "Dieter Fischer"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 1,
                            Name = "Ingrid Richter"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 1,
                            Name = "Clara Wagner"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 3,
                            Name = "Eva Schmidt"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 3,
                            Name = "Dieter Weber"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 3,
                            Name = "Eva Fischer"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 4,
                            Name = "Heinz Bauer"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 4,
                            Name = "Clara Fischer"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 3,
                            Name = "Dieter Richter"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 2,
                            Name = "Johann Fischer"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 1,
                            Name = "Friedrich Weber"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 1,
                            Name = "Clara Bauer"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 2,
                            Name = "Clara Meier"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 1,
                            Name = "Greta Weber"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 4,
                            Name = "Ingrid Schmidt"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 3,
                            Name = "Greta Schmidt"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 5,
                            Name = "Johann Schmidt"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 4,
                            Name = "Greta Meier"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 2,
                            Name = "Dieter Weber"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 1,
                            Name = "Bernd Wagner"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 2,
                            Name = "Johann Becker"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 1,
                            Name = "Heinz Weber"
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 3,
                            Name = "Anton Becker"
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 2,
                            Name = "Greta Schmidt"
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 5,
                            Name = "Johann Meier"
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 5,
                            Name = "Eva Becker"
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 4,
                            Name = "Dieter Weber"
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 1,
                            Name = "Bernd Schmidt"
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 5,
                            Name = "Bernd Weber"
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 3,
                            Name = "Heinz Wagner"
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 2,
                            Name = "Friedrich Weber"
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 5,
                            Name = "Heinz Schmidt"
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 5,
                            Name = "Ingrid Koch"
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 2,
                            Name = "Dieter Koch"
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 5,
                            Name = "Bernd Weber"
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 4,
                            Name = "Ingrid Bauer"
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 2,
                            Name = "Ingrid Bauer"
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 1,
                            Name = "Dieter Becker"
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 1,
                            Name = "Bernd Wagner"
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 1,
                            Name = "Heinz Weber"
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 1,
                            Name = "Bernd Koch"
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 4,
                            Name = "Eva Becker"
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 3,
                            Name = "Anton Bauer"
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 5,
                            Name = "Bernd Schmidt"
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 1,
                            Name = "Eva Richter"
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 2,
                            Name = "Heinz Bauer"
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 5,
                            Name = "Friedrich Bauer"
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 2,
                            Name = "Heinz Schmidt"
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 4,
                            Name = "Clara Becker"
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 4,
                            Name = "Friedrich Koch"
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 2,
                            Name = "Johann Weber"
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 5,
                            Name = "Friedrich Schmidt"
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 3,
                            Name = "Bernd Müller"
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 3,
                            Name = "Heinz Müller"
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 1,
                            Name = "Bernd Wagner"
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 4,
                            Name = "Dieter Meier"
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 2,
                            Name = "Clara Wagner"
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 2,
                            Name = "Anton Bauer"
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 5,
                            Name = "Heinz Meier"
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 1,
                            Name = "Greta Weber"
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 1,
                            Name = "Greta Becker"
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 1,
                            Name = "Ingrid Bauer"
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 1,
                            Name = "Ingrid Schmidt"
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 3,
                            Name = "Dieter Richter"
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 4,
                            Name = "Johann Richter"
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 5,
                            Name = "Heinz Becker"
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 5,
                            Name = "Heinz Müller"
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 3,
                            Name = "Dieter Koch"
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 4,
                            Name = "Friedrich Fischer"
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 5,
                            Name = "Eva Wagner"
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 5,
                            Name = "Johann Fischer"
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 4,
                            Name = "Eva Müller"
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 3,
                            Name = "Ingrid Becker"
                        },
                        new
                        {
                            Id = 92,
                            DepartmentId = 2,
                            Name = "Friedrich Weber"
                        },
                        new
                        {
                            Id = 93,
                            DepartmentId = 4,
                            Name = "Clara Meier"
                        },
                        new
                        {
                            Id = 94,
                            DepartmentId = 1,
                            Name = "Johann Becker"
                        },
                        new
                        {
                            Id = 95,
                            DepartmentId = 3,
                            Name = "Johann Weber"
                        },
                        new
                        {
                            Id = 96,
                            DepartmentId = 1,
                            Name = "Friedrich Fischer"
                        },
                        new
                        {
                            Id = 97,
                            DepartmentId = 1,
                            Name = "Clara Koch"
                        },
                        new
                        {
                            Id = 98,
                            DepartmentId = 3,
                            Name = "Anton Wagner"
                        },
                        new
                        {
                            Id = 99,
                            DepartmentId = 3,
                            Name = "Dieter Schmidt"
                        },
                        new
                        {
                            Id = 100,
                            DepartmentId = 3,
                            Name = "Ingrid Koch"
                        },
                        new
                        {
                            Id = 101,
                            DepartmentId = 2,
                            Name = "Ingrid Richter"
                        },
                        new
                        {
                            Id = 102,
                            DepartmentId = 5,
                            Name = "Heinz Fischer"
                        },
                        new
                        {
                            Id = 103,
                            DepartmentId = 4,
                            Name = "Friedrich Schmidt"
                        },
                        new
                        {
                            Id = 104,
                            DepartmentId = 3,
                            Name = "Dieter Becker"
                        },
                        new
                        {
                            Id = 105,
                            DepartmentId = 3,
                            Name = "Friedrich Meier"
                        },
                        new
                        {
                            Id = 106,
                            DepartmentId = 1,
                            Name = "Eva Meier"
                        },
                        new
                        {
                            Id = 107,
                            DepartmentId = 4,
                            Name = "Ingrid Richter"
                        },
                        new
                        {
                            Id = 108,
                            DepartmentId = 1,
                            Name = "Bernd Weber"
                        },
                        new
                        {
                            Id = 109,
                            DepartmentId = 5,
                            Name = "Johann Meier"
                        },
                        new
                        {
                            Id = 110,
                            DepartmentId = 2,
                            Name = "Greta Weber"
                        },
                        new
                        {
                            Id = 111,
                            DepartmentId = 5,
                            Name = "Dieter Meier"
                        },
                        new
                        {
                            Id = 112,
                            DepartmentId = 2,
                            Name = "Bernd Bauer"
                        },
                        new
                        {
                            Id = 113,
                            DepartmentId = 3,
                            Name = "Dieter Becker"
                        },
                        new
                        {
                            Id = 114,
                            DepartmentId = 3,
                            Name = "Anton Weber"
                        },
                        new
                        {
                            Id = 115,
                            DepartmentId = 3,
                            Name = "Friedrich Fischer"
                        },
                        new
                        {
                            Id = 116,
                            DepartmentId = 5,
                            Name = "Greta Bauer"
                        },
                        new
                        {
                            Id = 117,
                            DepartmentId = 5,
                            Name = "Johann Koch"
                        },
                        new
                        {
                            Id = 118,
                            DepartmentId = 5,
                            Name = "Ingrid Meier"
                        },
                        new
                        {
                            Id = 119,
                            DepartmentId = 4,
                            Name = "Johann Wagner"
                        },
                        new
                        {
                            Id = 120,
                            DepartmentId = 2,
                            Name = "Greta Müller"
                        },
                        new
                        {
                            Id = 121,
                            DepartmentId = 3,
                            Name = "Clara Fischer"
                        },
                        new
                        {
                            Id = 122,
                            DepartmentId = 2,
                            Name = "Heinz Koch"
                        },
                        new
                        {
                            Id = 123,
                            DepartmentId = 4,
                            Name = "Dieter Richter"
                        });
                });

            modelBuilder.Entity("Deskbuddy.Models.Occupancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Occupancies", (string)null);
                });

            modelBuilder.Entity("Deskbuddy.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Deskbuddy.Models.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Workplaces", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c19c4014-c8be-43a0-ad73-f63c87050feb",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "5b08c06c-8aab-422a-bbb5-898ad7f76ba6",
                            Name = "Sekretariat",
                            NormalizedName = "SEKRETARIAT"
                        },
                        new
                        {
                            Id = "696af5b0-898a-44da-85f4-fc1674f8df2a",
                            Name = "Mitarbeiter",
                            NormalizedName = "MITARBEITER"
                        },
                        new
                        {
                            Id = "57c8a05d-6ca2-4fd0-b345-3ffc012aa679",
                            Name = "Abteilungsleiter",
                            NormalizedName = "ABTEILUNGSLEITER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "aa167027-4226-4341-bc45-fd9a0748f70a",
                            RoleId = "c19c4014-c8be-43a0-ad73-f63c87050feb"
                        },
                        new
                        {
                            UserId = "75b19fb1-7184-4a1e-bfaf-39d157353db2",
                            RoleId = "5b08c06c-8aab-422a-bbb5-898ad7f76ba6"
                        },
                        new
                        {
                            UserId = "1f6695ef-d669-48b4-b194-bd92d17057e0",
                            RoleId = "696af5b0-898a-44da-85f4-fc1674f8df2a"
                        },
                        new
                        {
                            UserId = "902f1326-2d22-411a-8c06-6732ad46aff4",
                            RoleId = "57c8a05d-6ca2-4fd0-b345-3ffc012aa679"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Deskbuddy.Models.Employee", b =>
                {
                    b.HasOne("Deskbuddy.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Deskbuddy.Models.Occupancy", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deskbuddy.Models.Workplace", "Workplace")
                        .WithMany("Occupancies")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Deskbuddy.Models.Workplace", b =>
                {
                    b.HasOne("Deskbuddy.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Deskbuddy.Areas.Identity.Data.DeskbuddyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deskbuddy.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Deskbuddy.Models.Workplace", b =>
                {
                    b.Navigation("Occupancies");
                });
#pragma warning restore 612, 618
        }
    }
}
